services:
  ecommerce-e1-api:
    image: ecommerce-e1-api:latest
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile
    ports:
      - "8081:9999"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ecommerce-db-e1:5432/db_commerce
      - SPRING_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak-e1:8080/realms/istad
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak-e1:8080/realms/istad/protocol/openid-connect/certs
    networks:
      - e1-net

networks:
  e1-net:
    external: true